### ISSUE TITLE
Exploring other kinds of auth issues

### ISSUE THREAD

**Issue by edasque** [acouvreur/ssh-log-to-influx#42]
Based on the rsylog config (and I am guessing the parsing code in the container), am I right in thinking that this will only detect the bad password type of error: ```Failed password for username from 206.253.167.10 port 11111 ssh2```

but not these:
```
May 18 14:09:57 moebius sshd[24830]: Invalid user bob from 72.xx.xx.87 port 38124
May 18 14:09:57 moebius sshd[24830]: input_userauth_request: invalid user bob [preauth]
May 18 14:09:57 moebius sshd[24830]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:09:57 moebius sshd[24830]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:09:57 moebius sshd[24830]: Connection closed by 72.xx.xx.87 port 38124 [preauth]
May 18 14:10:09 moebius sshd[24847]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:10:09 moebius sshd[24847]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]
May 18 14:10:10 moebius sshd[24847]: Connection closed by 72.xx.xx.87 port 38126 [preauth]
```

That may be more common, since it's best practice to use ssh keys instead of passwords?

**Comment by acouvreur** [comment]
You are right.

I'm currently working on detecting PubkeyAuthentication errors.

`Invalid user bob from 72.xx.xx.87 port 38124`  is one of these indeed.

If you find any other valid error to catch, that will be nice. Thanks!

**Comment by edasque** [comment]
Awesome, good to hear. Do you know of a way to confirm that the rsyslog configuration works?

**Comment by acouvreur** [comment]
Do you mean this kind of configuration ?

```
template(name="OnlyMsg" type="string" string="%msg:::drop-last-lf%\n")
if $programname == 'sshd' then {
   if $msg startswith ' Failed' then {
      action(type="omfwd" target="127.0.0.1" port="7070" protocol="tcp" template="OnlyMsg")
   }
}
```

I don't know any other way to test it apart from using it directly and trying to dispatch message by logging into the system.

The configuration **will have to change to catch more errors**, we already restric the scope to the sshd logs so maybe accepting all logs is something to consider. And do the heavy work inside server.

**Comment by edasque** [comment]
Cool. One last suggestion, make your dashboard available on grafana.com or export it by clicking "Share" and "For External". As is it, it's really hard to re-use.

**Comment by acouvreur** [comment]
Good suggestion, just did it. Hower I'm using Grafana 7.1... So only compatible with grafana:master.

The reason why is because I need new features to join on the time range to have valid values of the last time the attack happend + the sum of the attack from the ip.
